package compiler

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// SchemaCompiler compiles multiple .graphql files into a single schema
type SchemaCompiler struct {
	sourceDir string
	outputFile string
}

// NewSchemaCompiler creates a new schema compiler
func NewSchemaCompiler(sourceDir, outputFile string) *SchemaCompiler {
	return &SchemaCompiler{
		sourceDir:  sourceDir,
		outputFile: outputFile,
	}
}

// Compile finds all .graphql files and concatenates them into a single schema
func (c *SchemaCompiler) Compile() error {
	// Find all .graphql files
	files, err := c.findGraphQLFiles()
	if err != nil {
		return fmt.Errorf("error finding .graphql files: %w", err)
	}

	if len(files) == 0 {
		return fmt.Errorf("no .graphql files found in: %s", c.sourceDir)
	}

	// Concatenate schemas
	schema, err := c.concatenateSchemas(files)
	if err != nil {
		return fmt.Errorf("error concatenating schemas: %w", err)
	}

	// Ensure output directory exists
	outputDir := filepath.Dir(c.outputFile)
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("error creating output directory: %w", err)
	}

	// Write compiled schema
	if err := os.WriteFile(c.outputFile, []byte(schema), 0644); err != nil {
		return fmt.Errorf("error writing schema file: %w", err)
	}

	return nil
}

// CompileIfNeeded compiles the schema only if source files are newer than output
func (c *SchemaCompiler) CompileIfNeeded() (bool, error) {
	// Check if output file exists
	outputInfo, err := os.Stat(c.outputFile)
	if os.IsNotExist(err) {
		// Output doesn't exist, compile
		if err := c.Compile(); err != nil {
			return false, err
		}
		return true, nil
	}
	if err != nil {
		return false, fmt.Errorf("error checking output file: %w", err)
	}

	// Find newest .graphql file
	newestTime, _, err := c.findNewestGraphQLFile()
	if err != nil {
		return false, err
	}

	// Compare timestamps
	if newestTime.After(outputInfo.ModTime()) {
		// Source is newer, recompile
		if err := c.Compile(); err != nil {
			return false, err
		}
		return true, nil
	}

	// Schema is up to date
	return false, nil
}

// findGraphQLFiles recursively finds all .graphql files
func (c *SchemaCompiler) findGraphQLFiles() ([]string, error) {
	var files []string

	err := filepath.Walk(c.sourceDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && strings.HasSuffix(path, ".graphql") {
			files = append(files, path)
		}
		return nil
	})

	// Sort for consistent output
	sort.Strings(files)

	return files, err
}

// findNewestGraphQLFile finds the newest .graphql file
func (c *SchemaCompiler) findNewestGraphQLFile() (time time.Time, path string, err error) {
	files, err := c.findGraphQLFiles()
	if err != nil {
		return time, "", err
	}

	for _, file := range files {
		info, err := os.Stat(file)
		if err != nil {
			continue
		}
		if info.ModTime().After(time) {
			time = info.ModTime()
			path = file
		}
	}

	return time, path, nil
}

// concatenateSchemas combines .graphql files into a single schema
func (c *SchemaCompiler) concatenateSchemas(files []string) (string, error) {
	var builder strings.Builder

	// Header
	builder.WriteString("# Auto-generated GraphQL Schema\n")
	builder.WriteString("# Generated by Rocket Schema Compiler\n")
	builder.WriteString("#\n")
	builder.WriteString("# Source files:\n")
	for _, file := range files {
		builder.WriteString(fmt.Sprintf("#   - %s\n", file))
	}
	builder.WriteString("\n")

	// Check if any file defines root types
	hasQueryType, hasMutationType := c.checkForRootTypes(files)

	// Add placeholder root types if not defined
	if !hasQueryType {
		builder.WriteString("type Query {\n")
		builder.WriteString("  _empty: String\n")
		builder.WriteString("}\n\n")
	}

	if !hasMutationType {
		builder.WriteString("type Mutation {\n")
		builder.WriteString("  _empty: String\n")
		builder.WriteString("}\n\n")
	}

	// Sort files: root types first, then others
	rootFiles, otherFiles := c.sortFilesByRootTypes(files)
	allFiles := append(rootFiles, otherFiles...)

	// Concatenate all files
	for _, file := range allFiles {
		content, err := os.ReadFile(file)
		if err != nil {
			return "", fmt.Errorf("error reading %s: %w", file, err)
		}

		builder.WriteString("# ============================================\n")
		builder.WriteString(fmt.Sprintf("# From: %s\n", file))
		builder.WriteString("# ============================================\n\n")
		builder.WriteString(string(content))
		builder.WriteString("\n\n")
	}

	return builder.String(), nil
}

// checkForRootTypes checks if any file defines root Query or Mutation types
func (c *SchemaCompiler) checkForRootTypes(files []string) (hasQuery, hasMutation bool) {
	for _, file := range files {
		content, err := os.ReadFile(file)
		if err != nil {
			continue
		}

		contentStr := string(content)
		if strings.Contains(contentStr, "type Query") && !strings.Contains(contentStr, "extend type Query") {
			hasQuery = true
		}
		if strings.Contains(contentStr, "type Mutation") && !strings.Contains(contentStr, "extend type Mutation") {
			hasMutation = true
		}
	}
	return hasQuery, hasMutation
}

// sortFilesByRootTypes separates files with root type definitions
func (c *SchemaCompiler) sortFilesByRootTypes(files []string) (rootFiles, otherFiles []string) {
	for _, file := range files {
		content, err := os.ReadFile(file)
		if err != nil {
			otherFiles = append(otherFiles, file)
			continue
		}

		contentStr := string(content)
		hasRootType := (strings.Contains(contentStr, "type Query") && !strings.Contains(contentStr, "extend type Query")) ||
			(strings.Contains(contentStr, "type Mutation") && !strings.Contains(contentStr, "extend type Mutation"))

		if hasRootType {
			rootFiles = append(rootFiles, file)
		} else {
			otherFiles = append(otherFiles, file)
		}
	}
	return rootFiles, otherFiles
}

